### PR TITLE
Fix Window Close action being ignored.

### LINKED ISSUE #41: Ctrl-W acts like it has no active window.
Using Ctrl-W to close the active window in PrpShop is inconsistent and rarely works as expected.  Nothing happens when pressing the key combination, however, clicking on any item (even the currently-selected item) in the tree view causes the next Ctrl-W to close the active window, at which point it returns to being an inactive command.  Highlighting another item will once again re-enable a single use of Ctrl-W.  Changing the active window in the MDI area has no effect and does not enable Ctrl-W to function.

Manually choosing Close from the Window menu works correctly every time.

### PR DESCRIPTION
**Pull request by Deledrius**
Fixes #41.

The Window Close action needs its context set in order to apply to the window and its subchildren.  Adding it as an action to the Tree as well will close windows as expected even if the tree is currently the active widget.

### CODE REVIEW

File: src/PrpShop/Main.cpp [hunk 1]
```diff
@@ -91,6 +91,7 @@ PrpShopMain::PrpShopMain()
     fActions[kFileSaveAs]->setShortcut(Qt::CTRL + Qt::SHIFT + Qt::Key_S);
     fActions[kFileExit]->setShortcut(Qt::ALT + Qt::Key_F4);
     fActions[kWindowClose]->setShortcut(Qt::CTRL + Qt::Key_W);
+    fActions[kWindowClose]->setShortcutContext(Qt::WidgetWithChildrenShortcut);
```
Comment (zrax) [inline src/PrpShop/Main.cpp:94]: Out of curiosity, does `Qt::ApplicationShortcut` also work without needing to add the action to the `fBrowserTree`?

Comment (Deledrius) [reply src/PrpShop/Main.cpp:94]: It seems like it should, doesn't it?  It was the first option I tried as it appeared to be the correct context, but it appears to have no effect whatsoever.  Only `Qt::WidgetWithChildrenShortcut` works as expected.

Comment (zrax) [reply src/PrpShop/Main.cpp:94]: Huh, strange...  I wish it was better documented >.>

**Review by zrax — APPROVED** [review]
